apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc2
  labels:
    app: poc2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc2
      version: v1
  template:
    metadata:
      labels:
        app: poc2
        version: v1
    spec:
      containers:
        - name: poc2
          image: "wunderpark/poc2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: poc2
  labels:
    app: poc2
    service: poc2
spec:
  selector:
    app: poc2
  ports:
    - port: 3000
      name: http
